# Generated by Django 5.2.7 on 2025-10-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_address1_shippingaddress_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='shipping_email',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
